forcible_charge:
  name: Forcible Charge
  description: Forcible Charge of the battery for a certain time
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar
    duration:
      name: Duration
      description: Duration of the charge
      required: true
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: "minutes"
          mode: box
    power:
      name: Power
      description: Wattage used for the charge
      required: true
      default: 1000
      selector:
        text:

forcible_discharge:
  name: Forcible Discharge
  description: Forcible Discharge of the battery for a certain time
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar
    duration:
      name: Duration
      description: Duration of the discharge
      required: true
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: "minutes"
          mode: box
    power:
      name: Power
      description: Wattage used for the discharge
      required: true
      default: 1000
      selector:
        text:

forcible_charge_soc:
  name: Forcible Charge to a SoC level
  description: Forcible Charge of the battery to a certain State of Charge level
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar
    target_soc:
      name: Target SoC
      description: State of Charge that must be reached
      required: true
      default: 50
      selector:
        number:
          min: 12
          max: 100
          unit_of_measurement: "%"
    power:
      name: Power
      description: Wattage used for the charge
      required: true
      default: 1000
      selector:
        text:

forcible_discharge_soc:
  name: Forcible Discharge to a SoC level
  description: Forcible Discharge of the battery to a certain State of Charge level
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar
    target_soc:
      name: Target SoC
      description: State of Charge that must be reached
      required: true
      default: 15
      selector:
        number:
          min: 12
          max: 100
          unit_of_measurement: "%"
    power:
      name: Power
      description: Wattage used for the discharge
      required: true
      default: 1000
      selector:
        text:

stop_forcible_charge:
  name: Stop the forcible charge or discharge
  description: Cancel the running forcible charge command
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar

active_power_control_unlimited_mode:
  name: Set Active Power Control to Unlimited mode
  description: Set Active Power Control to the default Unlimited mode
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar

set_maximum_feed_grid_power:
  name: Limit the power fed to the grid
  description: Sets Active Power Control to 'Power-limited grid connection' with the given wattage
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar
    power:
      name: Power
      description: Maximum Wattage
      required: true
      default: 0
      selector:
        text:

set_maximum_feed_grid_power_percentage:
  name: Limit the power fed to the grid
  description: Sets Active Power Control to 'Power-limited grid connection (%)' with the given percentage
  fields:
    device_id:
      name: Battery
      description: Must be a 'Connected Energy Storage' device
      required: true
      selector:
        device:
          integration: huawei_solar
    power_percentage:
      name: Power Percentage
      description: Maximum Percentage
      required: true
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"